# Tensor manipulation
Notes:
- by rows: dim=0 or axis=0

In [141]:
import torch

## 1. Basics

In [ ]:
# 1. Create Tensors
# Create a 1D tensor of values from 0 to 9.
x1 = torch.arange(0,10)
x1
# Create a 2D tensor of shape (3, 4) filled with ones.
x2 = torch.ones((3,4))
x2
# Create a 3D tensor of shape (2, 3, 4) with random numbers.
x3 = torch.rand((2,3,4))
x3

tensor([[[0.4202, 0.3971, 0.2049, 0.1357],
         [0.5071, 0.5500, 0.5149, 0.0085],
         [0.8282, 0.0826, 0.3955, 0.0076]],

        [[0.3579, 0.0661, 0.8363, 0.0521],
         [0.0598, 0.7473, 0.3525, 0.1741],
         [0.3582, 0.9962, 0.0011, 0.5400]]])

In [ ]:
# 2. Reshaping
# Given t = torch.arange(12), reshape it into shape (3, 4).
t = torch.arange(12)
# t = t.reshape(3,4)
t = torch.reshape(t,(3,4))
t

# Flatten it back to 1D.
# t = torch.flatten(t)
# t

# Add a new dimension so that the shape becomes (3, 4, 1).
# t_new = torch.unsqueeze(t,-1)
# t_new
t_new = t.view(3,4,1)
t_new.shape

torch.Size([3, 4, 1])

## Level 2: Operations

In [51]:
# 4. Math Ops

# Create two tensors of shape (2, 3) and compute:
t1 = torch.arange(0,2*3).view(2,3)
# print(t1)
t2 = torch.arange(1,2*3*2,2).view(2,3)
# print(t2)
# Elementwise sum
t1 + t2
# Elementwise product
t1 * t2
# Matrix multiplication
torch.matmul(t1,t2.reshape(3,2))

# 5. Broadcasting

# Add a 1D tensor [1, 2, 3] to each row of a (3, 3) tensor.
t3 = torch.ones(3,3)
t3
t31 = torch.arange(1,4)
t31
t3 + t31

# Multiply a column vector (3,1) with a row vector (1,3) and check the result.
t4 = torch.arange(3).view(-1,1)
t4
t41 = torch.arange(2,5).view(-1,3) # 3: should have 3 columns, -1 automatically reshape
print(t4.shape)
print(t41.shape)
# torch.matmul(t4,t41)

# 6. Masking
# Given x = torch.tensor([1, 3, 5, 2, 4]), extract all elements greater than 3.
x = torch.tensor([1, 3, 5, 2, 4])
# x = x[x > 3]
# x
# Replace all values less than 3 with 0.
x[x < 3] = 0
x

torch.Size([3, 1])
torch.Size([1, 3])


tensor([0, 3, 5, 0, 4])

## Level 3: Advanced

In [88]:
# 7. Stacking & Concatenation

# Stack three (2, 2) tensors into one (3, 2, 2) tensor.
t1 = torch.rand((2,2))
t2 = torch.rand((2,2))
t3 = torch.rand((2,2))
t = torch.stack((t1,t2,t3))
t.shape
# Concatenate two (2, 3) tensors along rows and along columns.
t1 = torch.rand((2,3))
t2 = torch.rand((2,3))
print(t1)
print(t2)
t = torch.concatenate((t1,t2)) # (4,3)
t = torch.concatenate((t1,t2),axis=1)
t

# 8. Reduction

# Given a random (5, 4) tensor, compute:
t = torch.arange(1,21).view(5,4)
print(t)
t.shape
# The sum of all elements
# t.sum()
# The mean across rows
t.mean(dim=1,dtype=float)

# The maximum value in each column
t.max(dim=0).values

# 9. One-hot Encoding
import torch.nn.functional as F

# Convert a tensor labels = torch.tensor([0, 2, 1, 3]) into a one-hot encoded matrix with 4 classes.
labels = torch.tensor([0, 2, 1, 3])
torch.eye(4)[labels]
# or
F.one_hot(labels,4)

# 10. Argmax & Sorting

# For a (5, 5) random tensor, find the index of the maximum element in each row.
t = torch.rand((5,5))
print(t)
t.max(dim=1)
# Sort the tensor along dimension 1.
t.sort(dim=1)
t

tensor([[0.3339, 0.0910, 0.1742],
        [0.8994, 0.6775, 0.0910]])
tensor([[0.0296, 0.0533, 0.9811],
        [0.8356, 0.2715, 0.4980]])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]])
tensor([[0.1193, 0.2512, 0.8670, 0.4018, 0.1750],
        [0.3471, 0.1563, 0.9880, 0.1569, 0.2139],
        [0.0608, 0.1097, 0.2891, 0.6043, 0.8331],
        [0.6538, 0.4702, 0.5107, 0.3513, 0.9148],
        [0.9001, 0.9661, 0.3254, 0.2918, 0.8615]])


tensor([[0.1193, 0.2512, 0.8670, 0.4018, 0.1750],
        [0.3471, 0.1563, 0.9880, 0.1569, 0.2139],
        [0.0608, 0.1097, 0.2891, 0.6043, 0.8331],
        [0.6538, 0.4702, 0.5107, 0.3513, 0.9148],
        [0.9001, 0.9661, 0.3254, 0.2918, 0.8615]])

## Challenge

In [140]:

# 11. Boolean Mask with 2D

# Create x = torch.arange(-5, 5).view(-1, 1).
x = torch.arange(-5, 5).view(-1, 1)
# print(x)
# Assign label 0 if x < -2, label 1 if -2 ≤ x < 2, and label 2 if x ≥ 2.

# Cannot do this way
x_new = torch.zeros_like(x)
x_new[[(x >= -2)] and [(x < 2)]] = 1
x_new[x < -2] = 0
x_new[x >=2] = 2
x_new


# 12. Simulate a Dataset

# Generate 100 random points in 2D ((100, 2)).
points = torch.rand((100,2))
points.shape
# Compute their Euclidean distance from the origin.
# eucl_dis = torch.norm(x)
eucl_dis = torch.sqrt((points[:,0]-0)**2 + (points[:,1]-0)**2)
print(eucl_dis)
eucl_dis = torch.sqrt(torch.sum(points ** 2, dim=1))
print(eucl_dis)

# Label them as:

dis_labels = torch.zeros_like(eucl_dis)
# Class 0 if distance < 1
dis_labels[eucl_dis < 1.0] = 0

# Class 1 if 1 ≤ distance < 2
dis_labels[(eucl_dis >= 1.0 )& (eucl_dis < 2.0) ] = 1

# Class 2 if distance ≥ 2
dis_labels[eucl_dis >= 2] = 2
dis_labels

tensor([1.1582, 0.5411, 0.7918, 0.7852, 0.8724, 1.0126, 0.3282, 1.1759, 0.9293,
        0.9685, 1.2606, 0.9657, 0.7273, 0.6114, 0.5644, 0.4446, 0.5386, 0.7372,
        0.6963, 0.4737, 0.3424, 0.3003, 1.1269, 1.1428, 0.1962, 0.6918, 1.2321,
        0.1683, 0.9720, 0.4319, 0.8644, 1.0048, 0.8000, 0.8849, 0.3798, 1.0035,
        0.0783, 1.1764, 0.6173, 0.6881, 1.0334, 0.7745, 0.9377, 1.0189, 0.3313,
        0.7981, 0.9767, 0.8672, 0.8600, 0.2779, 0.6296, 0.8229, 1.1472, 1.0225,
        0.9445, 0.8515, 0.7420, 1.0749, 0.7649, 0.9780, 0.6276, 1.2310, 0.4321,
        1.0584, 0.8292, 0.9281, 0.9267, 0.8504, 0.2869, 0.7699, 0.9704, 0.5854,
        0.8573, 0.3560, 0.5433, 0.7899, 1.0993, 0.5071, 0.7739, 1.0480, 0.5114,
        0.8163, 0.5629, 0.1080, 0.4797, 0.3782, 0.4114, 0.8205, 0.2116, 0.6155,
        0.9730, 0.4893, 0.5027, 0.6087, 0.4420, 1.0840, 0.9913, 1.2509, 0.6834,
        0.9425])
tensor([1.1582, 0.5411, 0.7918, 0.7852, 0.8724, 1.0126, 0.3282, 1.1759, 0.9293,
        0.9685, 1.2606,

tensor([1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
        0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
        0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 1., 0., 0.])